### ISSUE TITLE
Example code for "MKdECA" gives an error

### ISSUE THREAD

**Issue by tim-lenters** [OscarGOGO/Makurhini#12]
Hi,

I'm interested in using the MKdECA function and am experimenting a bit on the output it can provide. However, running the example code for this function doesn't work:

```
library(Makurhini)
library(sf)

data("list_forest_patches", package = "Makurhini")
data("study_area", package = "Makurhini")
class(list_forest_patches)

Max_attribute <- unit_convert(st_area(study_area), "m2", "ha")

dECA_test <- MK_dECA(nodes= list_forest_patches, attribute = NULL, area_unit = "ha",
                  distance = list(type= "centroid"), metric = "PC",
                  probability = 0.05, distance_thresholds = 5000,
                  LA = Max_attribute, plot= c("1993", "2003", "2007", "2011"),
                  intern = TRUE)
```
```
Error in MK_dECA(nodes = list_forest_patches, attribute = NULL, area_unit = "ha",  :                                                                     
  review ECA parameters: nodes, distance file or LA
```

Do you know why it raises this error, and how I can fix it?

Thanks in advance!

**Comment by OscarGOGO** [comment]
Hi,

I apologize, you are right, there is a bug with the MK_dECA function due to past changes in the short path estimation, now it can be estimated faster even if thousands of nodes are used. We will solve the problem today and at night (CT hour) or tomorrow it will be working normally. 

I'm glad you want to use the package. 

Best,
Oscar
