### ISSUE TITLE
error installing in ubuntu

### ISSUE THREAD

**Issue by jfmas** [OscarGOGO/Makurhini#19]
Hi
I get the following error installing Makurhini in ubuntu 
Installing package into ‘/home/jf/R/x86_64-pc-linux-gnu-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package ‘Makurhini’ ...
** using staged installation
** R
Error in parse(outFile) : 
  /tmp/Rtmph4c4Cd/R.INSTALL467434d9a5d8/Makurhini/R/distancefile.R:154:59: unexpected input
153:           x.1 <- colMeans(x[, c("x", "y")]); x.1 <- data.frame(x = x.1[[1]], y = x.1[[2]], Id = unique(x[[3]]))
154:           return(x.1)}, .progress = TRUE) |> st_as_sf(x = _
                                                               ^
ERROR: unable to collate and parse R files for package ‘Makurhini’
* removing ‘/home/jf/R/x86_64-pc-linux-gnu-library/4.1/Makurhini’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpIuzYBO/fileeaa56a5d2a7/Makurhini_2.0.6.tar.gz’ had non-zero exit status

**Comment by jfmas** [comment]
I resolved the issue installing a brand new R and then Makhurini as one of the first installed packages.

**Comment by OscarGOGO** [comment]
Hi! An apology for the delay. I'm glad it worked. Also, I added a new section to the Makurhini home page on Github (Makurhini on Linux) with six steps that we identified that may be helpful in installing Makurhuni on Linux. In addition, we removed the use of the native R pipe "|>" because it seems to cause problems.
